#!/bin/bash
clear
echo "==================================================" | lolcat
echo "                 ★ SSLAB UDP PANEL ★              " | lolcat
echo "==================================================" | lolcat
echo -e "  1) เพิ่มผู้ใช้งานใหม่ (Add User)"
echo -e "  2) แสดงผู้ใช้งานทั้งหมด (View Users)"
echo -e "  3) แก้ไขข้อมูลผู้ใช้งาน (Edit User)"
echo -e "  4) ลบผู้ใช้งาน (Delete User)"
echo -e "  5) ข้อมูลเซิร์ฟเวอร์ (Server Info)"
echo -e "  6) บล็อกบิททอร์เรนต์ (Torrent Blocker)"
echo -e "  7) ลบสคริปต์ติดตั้ง (Remove Script)"
echo -e "  8) เกี่ยวกับระบบ (About)"
echo -e "  9) รีสตาร์ทระบบ (Restart System)"
echo -e "  0) ออกจากเมนู (Exit)"
echo "==================================================" | lolcat
echo ""
read -p " • เลือกเมนูที่คุณต้องการใช้งาน [0-9] : " option

case $option in
    1) cd /etc/Sslablk/system && ./Adduser.sh ;;
    2) cd /etc/Sslablk/system && ./Userlist.sh ;;
    3) cd /etc/Sslablk/system && ./ChangeUser.sh ;;
    4) cd /etc/Sslablk/system && ./DelUser.sh ;;
    5) neofetch ;;
    6) cd /etc/Sslablk/system && ./torrent.sh ;;
    7) cd /etc/Sslablk/system && ./RemoveScript.sh ;;
    8) echo "สคริปต์นี้พัฒนาโดย SSLAB LK" ;;
    9) reboot ;;
    0) exit ;;
    *) echo "เลือกเมนูไม่ถูกต้อง" && sleep 1 && menu ;;
esac
