#!/bin/bash
clear
echo "==================================================" | lolcat
echo "                 ★ SSLAB UDP PANEL ★              " | lolcat
echo "==================================================" | lolcat
echo -e "  1) เพิ่มผู้ใช้งานใหม่"
echo -e "  2) แสดงผู้ใช้งานทั้งหมด"
echo -e "  3) แก้ไขข้อมูลผู้ใช้งาน"
echo -e "  4) ลบผู้ใช้งาน"
echo -e "  5) ข้อมูลเซิร์ฟเวอร์"
echo -e "  6) บล็อกบิททอร์เรนต์"
echo -e "  7) ลบสคริปต์ติดตั้ง"
echo -e "  8) เกี่ยวกับระบบ"
echo -e "  9) รีสตาร์ทระบบ"
echo -e "  0) ออกจากเมนู"
echo "==================================================" | lolcat
echo ""
read -p " • เลือกเมนูที่คุณต้องการใช้งาน [0-9] : " option

case $option in
    1) cd /etc/Sslablk/system && ./Adduser.sh ;;
    2) cd /etc/Sslablk/system && ./Userlist.sh ;;
    3) cd /etc/Sslablk/system && ./ChangeUser.sh ;;
    4) cd /etc/Sslablk/system && ./DelUser.sh ;;
    5) neofetch ;;
    6) cd /etc/Sslablk/system && ./torrent.sh ;;
    7) cd /etc/Sslablk/system && ./RemoveScript.sh ;;
    8) echo "สคริปต์นี้พัฒนาโดย ตอนนี้โสดแล้ว" ;;
    9) reboot ;;
    0) exit ;;
    *) echo "เลือกเมนูไม่ถูกต้อง" && sleep 1 && menu ;;
esac
